import { Indicator } from '../../../components/ppr-page/equipment-schema/equipment-schema-template/indicator-label/indicator-label.models';

export let mocks = (equipmentId: number): Indicator[] => {
    return [
        new Indicator({
            'id': '105001105001',
            'title': 'Уровень карналлита',
            'value': null,
            'percentage': null,
            'equipmentId': 105001,
            'equipmentTitle': 'Силосная башня № 1',
            'equipmentShortTitle': '',
            'indicatorId': 105001,
            'units': 'м',
            'minValue': 0.0,
            'maxValue': 27.8,
            'status': 0
        }),
        new Indicator({
            'id': '105001105002',
            'title': 'Масса карналита в Силосе',
            'value': null,
            'percentage': null,
            'equipmentId': 105001,
            'equipmentTitle': 'Силосная башня № 1',
            'equipmentShortTitle': '',
            'indicatorId': 105002,
            'units': 'т',
            'minValue': 0.0,
            'maxValue': 1875.0,
            'status': 0
        }),
        new Indicator({
            'id': '105002105001',
            'title': 'Уровень карналлита',
            'value': null,
            'percentage': null,
            'equipmentId': 105002,
            'equipmentTitle': 'Силосная башня № 2',
            'equipmentShortTitle': '',
            'indicatorId': 105001,
            'units': 'м',
            'minValue': 0.0,
            'maxValue': 27.8,
            'status': 0
        }),
        new Indicator({
            'id': '105002105002',
            'title': 'Масса карналита в Силосе',
            'value': null,
            'percentage': null,
            'equipmentId': 105002,
            'equipmentTitle': 'Силосная башня № 2',
            'equipmentShortTitle': '',
            'indicatorId': 105002,
            'units': 'т',
            'minValue': 0.0,
            'maxValue': 1875.0,
            'status': 0
        }),
        new Indicator({
            'id': '105003105001',
            'title': 'Уровень карналлита',
            'value': null,
            'percentage': null,
            'equipmentId': 105003,
            'equipmentTitle': 'Силосная башня № 3',
            'equipmentShortTitle': '',
            'indicatorId': 105001,
            'units': 'м',
            'minValue': 0.0,
            'maxValue': 27.8,
            'status': 0
        }),
        new Indicator({
            'id': '105003105002',
            'title': 'Масса карналита в Силосе',
            'value': null,
            'percentage': null,
            'equipmentId': 105003,
            'equipmentTitle': 'Силосная башня № 3',
            'equipmentShortTitle': '',
            'indicatorId': 105002,
            'units': 'т',
            'minValue': 0.0,
            'maxValue': 1875.0,
            'status': 0
        }),
        new Indicator({
            'id': '105004105001',
            'title': 'Уровень карналлита',
            'value': null,
            'percentage': null,
            'equipmentId': 105004,
            'equipmentTitle': 'Силосная башня № 4',
            'equipmentShortTitle': '',
            'indicatorId': 105001,
            'units': 'м',
            'minValue': 0.0,
            'maxValue': 27.8,
            'status': 0
        }),
        new Indicator({
            'id': '105004105002',
            'title': 'Масса карналита в Силосе',
            'value': null,
            'percentage': null,
            'equipmentId': 105004,
            'equipmentTitle': 'Силосная башня № 4',
            'equipmentShortTitle': '',
            'indicatorId': 105002,
            'units': 'т',
            'minValue': 0.0,
            'maxValue': 1875.0,
            'status': 0
        }),
        new Indicator({
            'id': '105005105001',
            'title': 'Уровень карналлита',
            'value': 14.797799491882325,
            'percentage': 53.22949457511627,
            'equipmentId': 105005,
            'equipmentTitle': 'Силосная башня № 5',
            'equipmentShortTitle': '',
            'indicatorId': 105001,
            'units': 'м',
            'minValue': 0.0,
            'maxValue': 27.8,
            'status': 1
        }),
        new Indicator({
            'id': '105005105002',
            'title': 'Масса карналита в Силосе',
            'value': 701.541830291748,
            'percentage': 37.415564282226562,
            'equipmentId': 105005,
            'equipmentTitle': 'Силосная башня № 5',
            'equipmentShortTitle': '',
            'indicatorId': 105002,
            'units': 'т',
            'minValue': 0.0,
            'maxValue': 1875.0,
            'status': 1
        }),
        new Indicator({
            'id': '105006105001',
            'title': 'Уровень карналлита',
            'value': null,
            'percentage': null,
            'equipmentId': 105006,
            'equipmentTitle': 'Силосная башня № 6',
            'equipmentShortTitle': '',
            'indicatorId': 105001,
            'units': 'м',
            'minValue': 0.0,
            'maxValue': 27.8,
            'status': 0
        }),
        new Indicator({
            'id': '105006105002',
            'title': 'Масса карналита в Силосе',
            'value': null,
            'percentage': null,
            'equipmentId': 105006,
            'equipmentTitle': 'Силосная башня № 6',
            'equipmentShortTitle': '',
            'indicatorId': 105002,
            'units': 'т',
            'minValue': 0.0,
            'maxValue': 1875.0,
            'status': 0
        }),
        new Indicator({
            'id': '105007105001',
            'title': 'Уровень карналлита',
            'value': null,
            'percentage': null,
            'equipmentId': 105007,
            'equipmentTitle': 'Силосная башня № 7',
            'equipmentShortTitle': '',
            'indicatorId': 105001,
            'units': 'м',
            'minValue': 0.0,
            'maxValue': 27.8,
            'status': 0
        }),
        new Indicator({
            'id': '105007105002',
            'title': 'Масса карналита в Силосе',
            'value': null,
            'percentage': null,
            'equipmentId': 105007,
            'equipmentTitle': 'Силосная башня № 7',
            'equipmentShortTitle': '',
            'indicatorId': 105002,
            'units': 'т',
            'minValue': 0.0,
            'maxValue': 1875.0,
            'status': 0
        }),
        new Indicator({
            'id': '105008105001',
            'title': 'Уровень карналлита',
            'value': -7.5,
            'percentage': -26.978417266187048,
            'equipmentId': 105008,
            'equipmentTitle': 'Силосная башня № 8',
            'equipmentShortTitle': '',
            'indicatorId': 105001,
            'units': 'м',
            'minValue': 0.0,
            'maxValue': 27.8,
            'status': 2
        }),
        new Indicator({
            'id': '105008105002',
            'title': 'Масса карналита в Силосе',
            'value': 2381.904,
            'percentage': 127.03488,
            'equipmentId': 105008,
            'equipmentTitle': 'Силосная башня № 8',
            'equipmentShortTitle': '',
            'indicatorId': 105002,
            'units': 'т',
            'minValue': 0.0,
            'maxValue': 1875.0,
            'status': 1
        })
    ];
};
