import { EquipmentRoute } from './equipment-schema.models';

export let equipmentRouteMap: Map<number, EquipmentRoute> = new Map<number, EquipmentRoute>([
    [101, new EquipmentRoute({ route: 'chlorine-compressor' })],
    [102, new EquipmentRoute({ route: 'refining-oven', forFacility: true })],
    [103, new EquipmentRoute({ route: 'magnesium-casting-plant', forFacility: true })],
    [105, new EquipmentRoute({ route: 'silo-towers', forFacility: true })],
    [106, new EquipmentRoute({ route: 'chlorinator' })],
    [107, new EquipmentRoute({ route: 'head-mixer', forFacility: true })],
    [108, new EquipmentRoute({ route: 'mixer-crystallizer', forFacility: true })],
    [109, new EquipmentRoute({ route: 'electrolyzer' })],
    [112, new EquipmentRoute({ route: 'pumping', forFacility: true })],
    [201, new EquipmentRoute({ route: 'tmk-titan-chlorinator', forFacility: false })],
    [202, new EquipmentRoute({ route: 'vanadium-chlorinator', forFacility: true })],
    [203, new EquipmentRoute({ route: 'shihtopodgotovka', forFacility: true })],
    [204, new EquipmentRoute({ route: 'equipment-production-purified-tt', forFacility: false })],
    [205, new EquipmentRoute({ route: 'equipment-storage', forFacility: true })],
    [301, new EquipmentRoute({ route: 'recovery-oven' })],
    [302, new EquipmentRoute({ route: 'distillation-furnaces' })],
    [303, new EquipmentRoute({ route: 'receiving-tanks', forFacility: true })],
    [304, new EquipmentRoute({ route: 'refrigerator' })],
    [305, new EquipmentRoute({ route: 'titan-gubka', forFacility: true })],
    [701, new EquipmentRoute({ route: 'tka', forFacility: false })],
    [702, new EquipmentRoute({ route: 'ov40', forFacility: false })],
    [703, new EquipmentRoute({ route: 'a1000', forFacility: false })],
    [1201, new EquipmentRoute({ route: 'ore-thermal-furnace', forFacility: true })],
    [1202, new EquipmentRoute({ route: 'futerovka', forFacility: true })],
    [1203, new EquipmentRoute({ route: 'dozator', forFacility: false })],
    [1204, new EquipmentRoute({ route: 'gazoo4sitka', forFacility: true })],
    [1402, new EquipmentRoute({ route: 'welging-plasma' })],
    [1403, new EquipmentRoute({ route: 'vacuum-arc-oven' })],
]);
